### ISSUE TITLE
Comparsion to hapi

### ISSUE THREAD

**Issue by floatdrop** [fistlabs/fist#231]
[hapi.js](https://github.com/hapijs/hapi) is a web and services application framework that (by description in readme) looks very similar to fist:

```
hapi is a simple to use configuration-centric framework with built-in support for 
input validation, caching, authentication, and other essential facilities for building 
web and services applications. hapi enables developers to focus on writing reusable 
application in a highly modular and prescriptive approach.
```

From fist readme:

 * Built-in scalable context logging - http://hapijs.com/tutorials/logging
 * Low coupling of application units - so does hapi: `reusable 
application in a highly modular and prescriptive approach`
 * Thin controllers - http://hapijs.com/tutorials#adding-routes
 * Built-in cache strategy (and local cache as default) - http://vawks.com/blog/2014/03/15/caching-with-hapi/
 * Plugin system and asynchronous application initialization - http://hapijs.com/tutorials/plugins

And there two items that I could not understand (nor find in docs):

 * Native (framework-level) modules - ?
 * Native data models - ?

Could you describe profit of using fist instead of hapi?

**Comment by golyshevd** [comment]
Hi, @floatdrop, thank for your interest. My bad, I have no deep knowledge of ```hapi```, but I'll try to answer you.

Logging
---------

Both fist and hapi provides context logging tools. But they do it in different ways.

Fist just expose context-bound logger instance for each context. You just directly call logger methods like ```log```, ```warn```, ```error``` and others. And your messages will be handled by corresponding handler. You can fine tune application root logger to write logs whatever.

Hapi provides a log event emitter. It is more cool (MVC). But it is hard to use (monster switch statement in log event handler I guess, single log handling point). And it is poorer (nor log levels, nor sprintf).

[read more](/docs/guides/using-logger.md) about logging fist applications

_Fist logging system is more powerful, familiar and easier_

Modularity
---------

Fist have ```units```, hapi have ```server methods```. It is not the same but similar.

Fist units is not a set of abilities, it is a blocks of business logic scenarios.

_It is not usual pattern but easy to get used. Fist units have same signature, can inherit from other units, can depend on other units._

Controllers
---------

```js
//  model
app.method('sum', function (a, b, done) {
    done(null, +a + +b);
});
app.route({
    //  route
    method: 'GET', path: '/sum/{a}/{b}',
    // controller
    handler: function (req, rep) {
        app.methods.sum(req.params.a, req.params.b, function (err, sum) {
             rep(sum);
        });
    }
});
```

Look at hapi controller. Business logic just in there. But there is no in fist controller. Sure, in real life hapi controllers more elegant.

```js
//  model
app.unit({
    name: 'sum',
    main: function (track, ctx) {
        return +ctx.params.a + +ctx.params.b;
    }
});
//  controller
app.unit({
    name: 'sum_page',
    deps: ['sum'],
    main: function (track, ctx) {
        track.send(ctx.result.sum);
    }
});
// route
app.route('GET /sum/<a>/<b>', 'sum_page');
```

I just want to say that in fist application we tried to split logic to units. Our controller just should check errors and apply template if necessary.

_You can once to write your base controller and then inherit all your controllers from it._

Cache
---------

Fist units can cache their results, Hapi server methods can cache their results.
I will not to compare it, it is so similar.

Seems like hapi cache is more powerful (hapi have more options for cache), but I did not understand, does hapi provide an ability to use separate cache instances for different server methods?

In fist applications we replace default local lru cache with memcached.

Plugins
---------

When I hear "need write plugin", I get bored. I want fist plugin to be a minimal entity of application code distribution and all the application code is set of little plugins.

External hapi plugins (distributed as npm modules) have two versions. And two names. npm package name, plugin name, npm package version, plugin version. Yes you can just specify pkg attribute, but why? hapi plugins have ```multiple``` option that allows the plugin to be registered multiple times with the same server. But it is strange.

Is it kludge for cases when plugin afraid of being installed a twice?

In fact, both fist and hapi plugins are similar and do their job. But fist plugins are more easier to use.

_Fist plugins uses peerDependencies to resolve conflicts (In fact does nothing and delegate the problems to npm). Fist plugins have much more simplier interface_

[more](https://github.com/fistlabs/fist/blob/master/docs/guides/using-plugins.md#using-plugins-guide) about fist plugins

Native modules
---------

My bad. It is about plugin loader. You just can create fist_plugins (or other) directory in
your project and all plugins will be loaded from there, also you can
install plugins from npm modules. Auto plugin loading is funny, you just add new plugin with your new unit and fist installs it automatically.

_You do not need do write any plugin installation code._

[read more](https://github.com/fistlabs/fist/blob/master/docs/guides/using-plugins.md#installation) about plugins installation

Native models
---------

The most popular reason of controller growing is creating models for views there.
Fist controllers should not contain any business logic.
But any controller's dependency can return result or throw error. This value will be automatically attached to dependant's execution context. We feel free to use this value as data-model.

```js
app.unit({
    name: 'sys.pid',
    main: function () {
        return process.pid;
    }
});
app.unit({
    name: 'sys.time',
    main: function () {
        return new Date();
    }
});
app.unit({
    name: 'index',
    deps: ['sys.pid', 'sys.time'],
    main: function (track, context) {
        track.send(context);
    }
});
app.route('GET /', 'index');
```

```
$ curl "http://localhost:1337/"
{
    params: { },
    errors: { },
    result: {
        sys: {
            pid: 21870,
            time: "2015-01-04T17:02:18.214Z"
        }
    }
}
```

_Native unobtrusive models are suitable to use it without any changes in your templates. See [context API](/docs/reference/context.md)_

During answering you, I have been little learned and read about hapi framework. Unfortunately I was never being happy to write application on hapi, but I will try as soon as I will get a chance. Hapi is similar to fist, but still different.

Good luck in choosing framework!

**Comment by floatdrop** [comment]
> Fist logging system is more powerful, familiar and easier

That's quite bold statement, hapi supports custom loggers with more features - as [logging-plugins](http://hapijs.com/tutorials/logging#logging-plugins) says. Does fist support custom loggers?

> Fist plugins uses peerDependencies to resolve conflicts (In fact does nothing and delegate the problems to npm). Fist plugins have much more simplier interface

This is stop-sign for many developers — we has enough problems with peerDependencies in past.

Thanks for the detailed comparsion thou.

**Comment by golyshevd** [comment]
> Does fist support custom loggers?
Fist [logger](https://www.npmjs.com/package/loggin) supports custom layouts and handlers for your logs. For example we have such config that do this:
* write ALL the messages to stdout in compact layout
* write WARNING+ messages to stderr using more verbose layout
* send ERROR+ messages to [sentry](https://www.getsentry.com/) with super verbose layout

Finally:
* all the logs in stdout
* only important stuff in stderr
* critical condition messages in sentry web-interface

> This is stop-sign for many developers — we has enough problems with peerDependencies in past.
It really had some problems in past, but now this feature working correctly. If we can't install two plugins peer-dependant on framework, it means one of two things:
* developers of plugins was specified too strictly versions . They should use ranges instead of strict versions.
* Theese plugins really do not support each other

Peer dependencies is the only correct way. Much more better then invent version resolution system by yourself. If you accidentally installed two same plugins with other versions you will get strange hard to find bugs.
