### ISSUE TITLE
track.send doesn't work with readable stream

### ISSUE THREAD

**Issue by gitim** [fistlabs/fist#283]
Hi! I wanted to serve static content in my project via fist, [here](https://github.com/gitim/test) simplified example what I am doing. I pass readable stream of test.css to track's send method, but get 404 error. Is it problem in my code or fist's? I can't understand from docs what I am doing wrong, could you help me to solve this problem?

**Comment by golyshevd** [comment]
Strange! I will check

**Comment by golyshevd** [comment]
It is a bug

**Comment by golyshevd** [comment]
Will fix in few hours

**Comment by gitim** [comment]
Thank you!

**Comment by golyshevd** [comment]
Fixed in 3.5.1

**Comment by gitim** [comment]
:+1:

**Comment by gitim** [comment]
Everything is good, so I am closing this.

**Comment by golyshevd** [comment]
Thanks for contributing!
